apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resume-builder
  annotations:
    kubernetes.io/ingress.global-static-ip-name: resume-builder-ip
  labels:
    app: resume-builder
spec:
  defaultBackend:
    service:
      name: resume-builder-backend
      port:
        number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: resume-builder-backend
  labels:
    app: resume-builder
spec:
  type: NodePort
  selector:
    app: resume-builder
    tier: web
  ports:
  - port: 8080
    targetPort: 3000